-- =============================================
-- EMAIL CAPTURE — marketing opt-ins + quiz leads
-- Run in the Massage Club Supabase project SQL editor.
-- =============================================

-- Marketing opt-ins (booking success card + end of profile setup)
create table if not exists public.marketing_optins (
  id bigint generated by default as identity primary key,
  email text,
  user_id uuid,
  source text,
  booking_ref text,
  created_at timestamptz not null default now()
);

grant insert on public.marketing_optins to anon, authenticated;
grant usage, select on sequence public.marketing_optins_id_seq to anon, authenticated;
grant all on public.marketing_optins to service_role;

alter table public.marketing_optins enable row level security;

drop policy if exists "marketing_optins_anon_insert" on public.marketing_optins;
create policy "marketing_optins_anon_insert" on public.marketing_optins
  for insert to anon, authenticated with check (true);
-- No select/update/delete policies on purpose: only service_role can read.

create index if not exists marketing_optins_created_idx on public.marketing_optins(created_at desc);
create index if not exists marketing_optins_email_idx on public.marketing_optins(email);

-- Quiz leads (optional "Email me my match" on the quiz result)
create table if not exists public.quiz_leads (
  id bigint generated by default as identity primary key,
  email text not null,
  result_slug text,
  created_at timestamptz not null default now()
);

grant insert on public.quiz_leads to anon, authenticated;
grant usage, select on sequence public.quiz_leads_id_seq to anon, authenticated;
grant all on public.quiz_leads to service_role;

alter table public.quiz_leads enable row level security;

drop policy if exists "quiz_leads_anon_insert" on public.quiz_leads;
create policy "quiz_leads_anon_insert" on public.quiz_leads
  for insert to anon, authenticated with check (true);
-- No select/update/delete policies on purpose: only service_role can read.

create index if not exists quiz_leads_created_idx on public.quiz_leads(created_at desc);

-- Profile flag used when a signed-in user opts in.
alter table public.profiles add column if not exists marketing_opt_in boolean default false;
alter table public.profiles add column if not exists marketing_opt_in_at timestamptz;
