-- =============================================
-- REFERRALS — customer affiliate links
-- Run this in Supabase SQL Editor.
-- Referrer earns €5 credit when their referee completes a booking.
-- Credit is applied on the referrer's next booking (marked in bookings.notes;
-- payment happens at studio so this is a "mention at studio" credit).
-- =============================================

-- 1. Add referral_code to profiles (unique short code)
alter table public.profiles
  add column if not exists referral_code text unique;

-- 2. Referrals: one row per (referrer -> referee) pair
create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references auth.users(id) on delete cascade,
  referred_user_id uuid references auth.users(id) on delete set null,
  referred_email text,
  first_booking_id bigint references public.bookings(id) on delete set null,
  credited boolean not null default false,
  credited_at timestamptz,
  created_at timestamptz not null default now(),
  unique(referrer_id, referred_user_id)
);

alter table public.referrals enable row level security;

-- Users see referrals where they are the referrer OR the referee
drop policy if exists "referrals_read_own" on public.referrals;
create policy "referrals_read_own" on public.referrals
  for select to authenticated
  using (auth.uid() = referrer_id or auth.uid() = referred_user_id);

-- Any authenticated user can insert a referral row where they are the referee
drop policy if exists "referrals_insert_as_referee" on public.referrals;
create policy "referrals_insert_as_referee" on public.referrals
  for insert to authenticated
  with check (auth.uid() = referred_user_id);

-- 3. Credits ledger: each row = one unused/used credit
create table if not exists public.referral_credits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount_cents integer not null default 500,       -- €5
  referral_id bigint references public.referrals(id) on delete set null,
  used_by_booking_id bigint references public.bookings(id) on delete set null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.referral_credits enable row level security;

drop policy if exists "credits_read_own" on public.referral_credits;
create policy "credits_read_own" on public.referral_credits
  for select to authenticated
  using (auth.uid() = user_id);

-- Insert allowed by the referee on behalf of the referrer (rewarding them)
drop policy if exists "credits_insert_reward" on public.referral_credits;
create policy "credits_insert_reward" on public.referral_credits
  for insert to authenticated
  with check (
    exists (
      select 1 from public.referrals r
      where r.id = referral_id
        and r.referrer_id = referral_credits.user_id
        and r.referred_user_id = auth.uid()
    )
  );

-- Credit owner can mark their own credit as used
drop policy if exists "credits_update_own" on public.referral_credits;
create policy "credits_update_own" on public.referral_credits
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists referral_credits_user_idx on public.referral_credits(user_id);
create index if not exists referrals_referrer_idx on public.referrals(referrer_id);
