-- =============================================
-- FAVOURITES — saved studios per account
-- Local (logged out) favourites live in localStorage and are migrated here
-- on the first sign-in.
-- =============================================

create table if not exists public.favourites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  studio_key text not null,
  studio_name text,
  created_at timestamptz not null default now(),
  unique (user_id, studio_key)
);

grant select, insert, update, delete on public.favourites to authenticated;
grant usage, select on sequence public.favourites_id_seq to authenticated;
grant all on public.favourites to service_role;

alter table public.favourites enable row level security;

drop policy if exists "favourites_own_select" on public.favourites;
create policy "favourites_own_select" on public.favourites
  for select to authenticated using (auth.uid() = user_id);

drop policy if exists "favourites_own_insert" on public.favourites;
create policy "favourites_own_insert" on public.favourites
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "favourites_own_update" on public.favourites;
create policy "favourites_own_update" on public.favourites
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "favourites_own_delete" on public.favourites;
create policy "favourites_own_delete" on public.favourites
  for delete to authenticated using (auth.uid() = user_id);

create index if not exists favourites_user_idx on public.favourites(user_id);

-- Quiz result kept on the profile for signed-in visitors.
alter table public.profiles add column if not exists quiz_result_slug text;
alter table public.profiles add column if not exists quiz_result_at timestamptz;
