-- Survey responses table
create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  q1_how_book text,
  q2_pain_point text,
  q3_frequency text,
  q4_willing_to_pay text,
  q5_membership text,
  q6_features text,
  email text,
  source text default 'survey_mvp',
  submitted_at timestamptz default now()
);

alter table public.survey_responses enable row level security;

-- Public insert (no auth needed for anonymous survey)
create policy "public_insert_survey" on public.survey_responses
  for insert to anon, authenticated with check (true);

-- No read policy (keep responses private)
