-- =============================================
-- BOOKING LEADS — abandoned-booking capture
-- Run in the Massage Club Supabase project SQL editor.
-- =============================================

create table if not exists public.booking_leads (
  id bigint generated by default as identity primary key,
  email text not null,
  partner_slug text,
  service_name text,
  booking_date text,
  booking_time text,
  created_at timestamptz not null default now()
);

-- Data API access: anonymous visitors may only INSERT. No client reads.
grant insert on public.booking_leads to anon, authenticated;
grant usage, select on sequence public.booking_leads_id_seq to anon, authenticated;
grant all on public.booking_leads to service_role;

alter table public.booking_leads enable row level security;

drop policy if exists "booking_leads_anon_insert" on public.booking_leads;
create policy "booking_leads_anon_insert" on public.booking_leads
  for insert to anon, authenticated with check (true);

-- No select/update/delete policies on purpose: only service_role can read.

create index if not exists booking_leads_created_idx on public.booking_leads(created_at desc);
create index if not exists booking_leads_slug_idx on public.booking_leads(partner_slug);
