-- =============================================
-- MASSAGE CLUB MVP SCHEMA — Minimal Working Version
-- Run this in Supabase SQL Editor
-- https://jglftdstrowwckwqmpue.supabase.co/project/_/sql
-- =============================================

-- BOOKINGS table (what the app writes to)
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  client_name text not null,
  client_email text,
  client_phone text,
  spa_name text not null,
  massage_type text,
  booking_date text not null,        -- ISO date string e.g. "2026-05-10"
  booking_time text not null,       -- time string e.g. "14:00"
  duration integer default 60,      -- minutes
  pressure text,
  focus_areas text[],
  add_ons text[],
  notes text,
  status text default 'confirmed' check (status in ('pending', 'confirmed', 'cancelled')),
  booking_ref text,                 -- human readable e.g. "MR-2026-0042"
  studio_id text,                   -- references MASSAGES id from data.ts
  customer_id text,                  -- from app auth/session
  created_at timestamptz default now()
);

-- LEADS table (email capture)
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  email text not null,
  name text,
  source text default 'app',
  created_at timestamptz default now()
);

-- =============================================
-- Row Level Security — public read/write for MVP
-- =============================================
alter table public.bookings enable row level security;
alter table public.leads enable row level security;

-- Anyone can insert bookings (no auth needed for MVP)
create policy "public_insert_bookings" on public.bookings
  for insert to anon, authenticated with check (true);

-- Anyone can read bookings (so customer confirmation works)
create policy "public_read_bookings" on public.bookings
  for select to anon, authenticated using (true);

-- Anyone can insert leads
create policy "public_insert_leads" on public.leads
  for insert to anon, authenticated with check (true);

-- =============================================
-- INDEXES for fast lookups
-- =============================================
create index if not exists bookings_spa_name_idx on public.bookings(spa_name);
create index if not exists bookings_date_idx on public.bookings(booking_date);
create index if not exists bookings_status_idx on public.bookings(status);
create index if not exists bookings_created_idx on public.bookings(created_at desc);
